version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080" # Hub exposed on port 4444
      - "50000:50000"
    volumes:
      - ./volumes/master:/var/jenkins_home