version: "3"
services:
  hub:
    image: selenium/hub:4.20
  chrome:
    image: selenium/node-chrome:4.20
    shm_size: "2g" # Required for Chrome and Firefox nodes in Docker
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file: .env
