version: "3"
services:
  hub:
    image: selenium/hub:4.20
  chrome:
    image: selenium/node-chrome:4.20
    shm_size: "2g" # Required for Chrome and Firefox nodes in Docker
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub # Hub hostname
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSION=true
      - SE_NODE_MAX_SESSIONS=1 # Maximum sessions for Chrome node
      - SE_VNC_NO_PASSWORD=1
